Project #3 Positioning and Floating
cvilla714/floating pull request #2
Opened 2020-08-26 20:08 UTC by cvilla714

On this branch, we created all of the code, the top navigation bar, the content for the page, the side images, bottom navigation bar, and footer as well.

2020-08-26 21:16 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

  ### Hi team, you guys did a very good job so far!
  #### I can see that you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [ ] The NY Times logo should be a link (link to page) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png)from Pathwright)
- [ ] Please Increase the width of your text column and use `heading` tags to refeer to topics like ‘As Big as It Gets’
![image](https://user-images.githubusercontent.com/56762529/91356376-f1d40900-e7c5-11ea-873e-e9b081798b6f.png)
- Original one
![image](https://user-images.githubusercontent.com/56762529/91356460-18923f80-e7c6-11ea-83fc-78648b181159.png)
- [ ] This page should have an `<aside>` tag for Editor's picks section on the righmost side, not a `<div>`. ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png)from Pathwright)

- [x] The Elements aligned should have a combination of all three techniques (float, flex and grid). ([Screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png)from Pathwright) and ([Screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png)from Odin) Looks like you guys forgeted to use the float rule. Kindly implement it 💪
- [ ] Your Editor's Pick article have images too small, please make them as the same size of the original one
![image](https://user-images.githubusercontent.com/56762529/91355775-0cf24900-e7c5-11ea-9192-2da6e967b59b.png)
- [ ] Your section is not centralized, please fix that 
![image](https://user-images.githubusercontent.com/56762529/91356032-6195c400-e7c5-11ea-8d0e-c1c65313f52d.png)
- Original one:
![image](https://user-images.githubusercontent.com/56762529/91356116-838f4680-e7c5-11ea-9a55-cffb4e70a8e9.png)

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [ ] ❌ Your project have linter errors, fix them.
- [ ] Rename your classes to make it descriptive (For example: what `.one` means?)
![image](https://user-images.githubusercontent.com/56762529/91356543-38c1fe80-e7c6-11ea-9f30-be97aef34501.png)
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/91355468-91909780-e7c4-11ea-9f82-260c00919946.png)

- [ ] Your code is throwing some errors and warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them. 
![image](https://user-images.githubusercontent.com/56762529/91355511-a0774a00-e7c4-11ea-9301-ff7dcf6ffd8e.png)

- [ ] Please delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
:x: **commented piece of codes** /* `.nav { color: red;}` */  
:heavy_check_mark: **comments about code** /*Navigation */  
- [ ] Remove the img folder from css folder.
- [ ] Kindly remember to make a descriptive README.md (add a brief description of your project) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/))

## [OPTIONAL CHANGES]
- [ ] Add a favicon to make it more similar to the original page;
- [ ] Improve your names at the REAMDE.md (adding your first and last names)

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀
<img src="https://media1.giphy.com/media/UjCXeFnYcI2R2/giphy.gif?cid=ecf05e47f85sszmncvz9gstxysd956tlk5y2gojz9vumla10&amp;rid=giphy.gif">
  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-26 21:16 UTC, kevincappuccino commented on README.md
>  Additional description about the project and its features.
Add a description here

2020-08-26 21:16 UTC, kevincappuccino commented on README.md
> +- Linkedin: [linkedin](https://www.linkedin.com/in/cosmel-villalobos-1900531aa/)
inside the [  ] add your social medias. e.g.: Instead of @githubhandle add your @username

2020-08-26 21:16 UTC, kevincappuccino commented on README.md
> +- Linkedin: [linkedin](https://www.linkedin.com/in/abmasadullah/)
inside the [  ] add your social medias. e.g.: Instead of @githubhandle add your @username

2020-08-26 21:19 UTC, kevincappuccino commented on index.html
> +        <!-- <img src="/css/pictures/mainpicture.jpg" alt="" /> -->
Please remove this commented code.

2020-08-27 06:38 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

### Hello @cvilla714 and @abmasadullah :wave: 

### You have done an amazing job implementing almost all of the changes requested by the previous TSE, but we still need to fix these:

- [x] Your linters are still failing, please fix it.

- [x] You still didn't remove the images folder from your css folder, you should put that folder in the root, so your project becomes more organized.

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-27 16:03 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

now you can merge to master your project is approved

## Happy Coding :tophat:

2020-08-27 16:16 UTC, merged